spring:
  # Configuracion MongoDB remoto
  data:
    mongodb:
      uri: mongodb+srv://mean_user:EWpWinEnfJ2nc32R@cluster0.hcqaq.mongodb.net/demo-mongodb?authSource=admin&replicaSet=atlas-m2z4np-shard-0&readPreference=primary&ssl=true

  # Configuracion MYSQL local
  datasource:
    url: jdbc:mysql://localhost:3306/nttdataDB?serverTimezone=UTC
    username: root
    password: root123$
  jpa:
    hibernate:
      ddl-auto: update